spring:
  application:
    name: kafka-springboot
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payments-consumer-group
      auto-offset-reset: earliest
    producer:
      properties:
        partitioner.class: com.example.kafka_springboot.kafka.RoundRobinPartitioner
