logging:
  level:
    root: WARN
    com.example: INFO
    org.apache.kafka.streams: WARN
    org.springframework.kafka: WARN
    org.apache.kafka.clients: WARN
    org.apache.kafka.common: WARN

spring:
  application:
    name: kafka-springboot
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: payments_user
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8085
    consumer:
      session.timeout.ms: 10000
      heartbeat.interval.ms: 3000
    streams:
      application-id: payment-streams-app
      cleanup:
        on-startup: true
      properties:
        schema.registry.url: http://localhost:8085
